# Generated by Django 4.1.1 on 2022-09-12 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='end date'),
        ),
    ]
