# Generated by Django 4.1.1 on 2022-09-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_choice_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
